version: '3.8'


services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    hostname: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
  broker:
    image: confluentinc/cp-kafka:latest
    hostname: broker
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "29092:9092"
    depends_on:
      - zookeeper
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: "vitalijprokopenya"
      POSTGRES_PASSWORD: "1234"
    ports:
      - "5431:5432"
  producer:
    image: producer
    environment:
      kafkaURL: broker:9092
      topic: topic1
    depends_on:
      - broker
  consumer:
    image: consumer
    environment:
      POSTGRES_PORT: "5432"
      kafkaURL: broker:9092
      topic: topic1